// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sex                  string   `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	Other                *Birth   `protobuf:"bytes,4,opt,name=other,proto3" json:"other,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *User) GetOther() *Birth {
	if m != nil {
		return m.Other
	}
	return nil
}

type Birth struct {
	Year                 uint32   `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                uint32   `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day                  uint32   `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	Country              string   `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	City                 string   `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Birth) Reset()         { *m = Birth{} }
func (m *Birth) String() string { return proto.CompactTextString(m) }
func (*Birth) ProtoMessage()    {}
func (*Birth) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *Birth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Birth.Unmarshal(m, b)
}
func (m *Birth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Birth.Marshal(b, m, deterministic)
}
func (m *Birth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Birth.Merge(m, src)
}
func (m *Birth) XXX_Size() int {
	return xxx_messageInfo_Birth.Size(m)
}
func (m *Birth) XXX_DiscardUnknown() {
	xxx_messageInfo_Birth.DiscardUnknown(m)
}

var xxx_messageInfo_Birth proto.InternalMessageInfo

func (m *Birth) GetYear() uint32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Birth) GetMonth() uint32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Birth) GetDay() uint32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *Birth) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Birth) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "protocol.user")
	proto.RegisterType((*Birth)(nil), "protocol.birth")
}

func init() {
	proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6)
}

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xc1, 0x6a, 0x85, 0x30,
	0x10, 0x45, 0x89, 0x9a, 0xb6, 0x4e, 0x49, 0x5b, 0x86, 0x2e, 0xb2, 0x14, 0xa1, 0xe0, 0xca, 0x45,
	0xfb, 0x27, 0xf9, 0x83, 0x18, 0x03, 0x06, 0xd4, 0xd8, 0x18, 0xc1, 0xfc, 0xfd, 0x23, 0xe3, 0x73,
	0x95, 0x73, 0x33, 0x70, 0xcf, 0x05, 0x61, 0x4f, 0xbd, 0x6c, 0xb3, 0xed, 0xb7, 0xe0, 0xa3, 0xc7,
	0x37, 0x7a, 0x8c, 0x9f, 0x5b, 0x03, 0xd5, 0xb1, 0xdb, 0x80, 0x1f, 0x50, 0xb8, 0x51, 0xb2, 0x86,
	0x75, 0x42, 0x15, 0x6e, 0x44, 0x84, 0x6a, 0xd5, 0x8b, 0x95, 0x45, 0xc3, 0xba, 0x5a, 0x11, 0xe3,
	0x17, 0x94, 0xbb, 0x3d, 0x65, 0x49, 0x5f, 0x19, 0xf1, 0x07, 0xb8, 0x8f, 0x93, 0x0d, 0xb2, 0x6a,
	0x58, 0xf7, 0xfe, 0xfb, 0xd9, 0xdf, 0xbd, 0xfd, 0xe0, 0x42, 0x9c, 0xd4, 0x75, 0x6d, 0xff, 0x81,
	0x53, 0xce, 0xad, 0xc9, 0xea, 0xf0, 0xf4, 0x10, 0xe3, 0x37, 0xf0, 0xc5, 0xaf, 0x71, 0x22, 0x95,
	0x50, 0x57, 0xc8, 0xae, 0x51, 0x27, 0x72, 0x09, 0x95, 0x11, 0x25, 0xbc, 0x1a, 0x7f, 0xac, 0x31,
	0x24, 0xb2, 0xd5, 0xea, 0x8e, 0xb9, 0xd5, 0xb8, 0x98, 0x24, 0xbf, 0xb6, 0x66, 0x1e, 0x5e, 0x68,
	0xc9, 0xdf, 0x23, 0x00, 0x00, 0xff, 0xff, 0x95, 0x4b, 0x26, 0x46, 0xf9, 0x00, 0x00, 0x00,
}
