// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DoubleItem struct {
	Value1               float64  `protobuf:"fixed64,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               float64  `protobuf:"fixed64,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               float64  `protobuf:"fixed64,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               float64  `protobuf:"fixed64,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               float64  `protobuf:"fixed64,5,opt,name=value5,proto3" json:"value5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoubleItem) Reset()         { *m = DoubleItem{} }
func (m *DoubleItem) String() string { return proto.CompactTextString(m) }
func (*DoubleItem) ProtoMessage()    {}
func (*DoubleItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *DoubleItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleItem.Unmarshal(m, b)
}
func (m *DoubleItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleItem.Marshal(b, m, deterministic)
}
func (m *DoubleItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleItem.Merge(m, src)
}
func (m *DoubleItem) XXX_Size() int {
	return xxx_messageInfo_DoubleItem.Size(m)
}
func (m *DoubleItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleItem.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleItem proto.InternalMessageInfo

func (m *DoubleItem) GetValue1() float64 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *DoubleItem) GetValue2() float64 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *DoubleItem) GetValue3() float64 {
	if m != nil {
		return m.Value3
	}
	return 0
}

func (m *DoubleItem) GetValue4() float64 {
	if m != nil {
		return m.Value4
	}
	return 0
}

func (m *DoubleItem) GetValue5() float64 {
	if m != nil {
		return m.Value5
	}
	return 0
}

type FloatItem struct {
	Value1               float32  `protobuf:"fixed32,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               float32  `protobuf:"fixed32,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               float32  `protobuf:"fixed32,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               float32  `protobuf:"fixed32,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               float32  `protobuf:"fixed32,5,opt,name=value5,proto3" json:"value5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FloatItem) Reset()         { *m = FloatItem{} }
func (m *FloatItem) String() string { return proto.CompactTextString(m) }
func (*FloatItem) ProtoMessage()    {}
func (*FloatItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *FloatItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FloatItem.Unmarshal(m, b)
}
func (m *FloatItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FloatItem.Marshal(b, m, deterministic)
}
func (m *FloatItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FloatItem.Merge(m, src)
}
func (m *FloatItem) XXX_Size() int {
	return xxx_messageInfo_FloatItem.Size(m)
}
func (m *FloatItem) XXX_DiscardUnknown() {
	xxx_messageInfo_FloatItem.DiscardUnknown(m)
}

var xxx_messageInfo_FloatItem proto.InternalMessageInfo

func (m *FloatItem) GetValue1() float32 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *FloatItem) GetValue2() float32 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *FloatItem) GetValue3() float32 {
	if m != nil {
		return m.Value3
	}
	return 0
}

func (m *FloatItem) GetValue4() float32 {
	if m != nil {
		return m.Value4
	}
	return 0
}

func (m *FloatItem) GetValue5() float32 {
	if m != nil {
		return m.Value5
	}
	return 0
}

type Int32Item struct {
	Value1               int32    `protobuf:"varint,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               int32    `protobuf:"varint,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               int32    `protobuf:"varint,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               int32    `protobuf:"varint,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               int32    `protobuf:"varint,5,opt,name=value5,proto3" json:"value5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32Item) Reset()         { *m = Int32Item{} }
func (m *Int32Item) String() string { return proto.CompactTextString(m) }
func (*Int32Item) ProtoMessage()    {}
func (*Int32Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *Int32Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32Item.Unmarshal(m, b)
}
func (m *Int32Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32Item.Marshal(b, m, deterministic)
}
func (m *Int32Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32Item.Merge(m, src)
}
func (m *Int32Item) XXX_Size() int {
	return xxx_messageInfo_Int32Item.Size(m)
}
func (m *Int32Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32Item.DiscardUnknown(m)
}

var xxx_messageInfo_Int32Item proto.InternalMessageInfo

func (m *Int32Item) GetValue1() int32 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *Int32Item) GetValue2() int32 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *Int32Item) GetValue3() int32 {
	if m != nil {
		return m.Value3
	}
	return 0
}

func (m *Int32Item) GetValue4() int32 {
	if m != nil {
		return m.Value4
	}
	return 0
}

func (m *Int32Item) GetValue5() int32 {
	if m != nil {
		return m.Value5
	}
	return 0
}

type Int64Item struct {
	Value1               int64    `protobuf:"varint,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               int64    `protobuf:"varint,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               int64    `protobuf:"varint,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               int64    `protobuf:"varint,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               int64    `protobuf:"varint,5,opt,name=value5,proto3" json:"value5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Item) Reset()         { *m = Int64Item{} }
func (m *Int64Item) String() string { return proto.CompactTextString(m) }
func (*Int64Item) ProtoMessage()    {}
func (*Int64Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{3}
}

func (m *Int64Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Item.Unmarshal(m, b)
}
func (m *Int64Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Item.Marshal(b, m, deterministic)
}
func (m *Int64Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Item.Merge(m, src)
}
func (m *Int64Item) XXX_Size() int {
	return xxx_messageInfo_Int64Item.Size(m)
}
func (m *Int64Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Item.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Item proto.InternalMessageInfo

func (m *Int64Item) GetValue1() int64 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *Int64Item) GetValue2() int64 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *Int64Item) GetValue3() int64 {
	if m != nil {
		return m.Value3
	}
	return 0
}

func (m *Int64Item) GetValue4() int64 {
	if m != nil {
		return m.Value4
	}
	return 0
}

func (m *Int64Item) GetValue5() int64 {
	if m != nil {
		return m.Value5
	}
	return 0
}

type Uint32Item struct {
	Value1               uint32   `protobuf:"varint,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               uint32   `protobuf:"varint,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               uint32   `protobuf:"varint,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               uint32   `protobuf:"varint,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               uint32   `protobuf:"varint,5,opt,name=value5,proto3" json:"value5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Uint32Item) Reset()         { *m = Uint32Item{} }
func (m *Uint32Item) String() string { return proto.CompactTextString(m) }
func (*Uint32Item) ProtoMessage()    {}
func (*Uint32Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{4}
}

func (m *Uint32Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uint32Item.Unmarshal(m, b)
}
func (m *Uint32Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uint32Item.Marshal(b, m, deterministic)
}
func (m *Uint32Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uint32Item.Merge(m, src)
}
func (m *Uint32Item) XXX_Size() int {
	return xxx_messageInfo_Uint32Item.Size(m)
}
func (m *Uint32Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Uint32Item.DiscardUnknown(m)
}

var xxx_messageInfo_Uint32Item proto.InternalMessageInfo

func (m *Uint32Item) GetValue1() uint32 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *Uint32Item) GetValue2() uint32 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *Uint32Item) GetValue3() uint32 {
	if m != nil {
		return m.Value3
	}
	return 0
}

func (m *Uint32Item) GetValue4() uint32 {
	if m != nil {
		return m.Value4
	}
	return 0
}

func (m *Uint32Item) GetValue5() uint32 {
	if m != nil {
		return m.Value5
	}
	return 0
}

type Uint64Item struct {
	Value1               uint64   `protobuf:"varint,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               uint64   `protobuf:"varint,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               uint64   `protobuf:"varint,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               uint64   `protobuf:"varint,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               uint64   `protobuf:"varint,5,opt,name=value5,proto3" json:"value5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Uint64Item) Reset()         { *m = Uint64Item{} }
func (m *Uint64Item) String() string { return proto.CompactTextString(m) }
func (*Uint64Item) ProtoMessage()    {}
func (*Uint64Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{5}
}

func (m *Uint64Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uint64Item.Unmarshal(m, b)
}
func (m *Uint64Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uint64Item.Marshal(b, m, deterministic)
}
func (m *Uint64Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uint64Item.Merge(m, src)
}
func (m *Uint64Item) XXX_Size() int {
	return xxx_messageInfo_Uint64Item.Size(m)
}
func (m *Uint64Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Uint64Item.DiscardUnknown(m)
}

var xxx_messageInfo_Uint64Item proto.InternalMessageInfo

func (m *Uint64Item) GetValue1() uint64 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *Uint64Item) GetValue2() uint64 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *Uint64Item) GetValue3() uint64 {
	if m != nil {
		return m.Value3
	}
	return 0
}

func (m *Uint64Item) GetValue4() uint64 {
	if m != nil {
		return m.Value4
	}
	return 0
}

func (m *Uint64Item) GetValue5() uint64 {
	if m != nil {
		return m.Value5
	}
	return 0
}

type Sint32Item struct {
	Value1               int32    `protobuf:"zigzag32,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               int32    `protobuf:"zigzag32,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               int32    `protobuf:"zigzag32,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               int32    `protobuf:"zigzag32,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               int32    `protobuf:"zigzag32,5,opt,name=value5,proto3" json:"value5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sint32Item) Reset()         { *m = Sint32Item{} }
func (m *Sint32Item) String() string { return proto.CompactTextString(m) }
func (*Sint32Item) ProtoMessage()    {}
func (*Sint32Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{6}
}

func (m *Sint32Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sint32Item.Unmarshal(m, b)
}
func (m *Sint32Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sint32Item.Marshal(b, m, deterministic)
}
func (m *Sint32Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sint32Item.Merge(m, src)
}
func (m *Sint32Item) XXX_Size() int {
	return xxx_messageInfo_Sint32Item.Size(m)
}
func (m *Sint32Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Sint32Item.DiscardUnknown(m)
}

var xxx_messageInfo_Sint32Item proto.InternalMessageInfo

func (m *Sint32Item) GetValue1() int32 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *Sint32Item) GetValue2() int32 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *Sint32Item) GetValue3() int32 {
	if m != nil {
		return m.Value3
	}
	return 0
}

func (m *Sint32Item) GetValue4() int32 {
	if m != nil {
		return m.Value4
	}
	return 0
}

func (m *Sint32Item) GetValue5() int32 {
	if m != nil {
		return m.Value5
	}
	return 0
}

type Sint64Item struct {
	Value1               int64    `protobuf:"zigzag64,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               int64    `protobuf:"zigzag64,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               int64    `protobuf:"zigzag64,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               int64    `protobuf:"zigzag64,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               int64    `protobuf:"zigzag64,5,opt,name=value5,proto3" json:"value5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sint64Item) Reset()         { *m = Sint64Item{} }
func (m *Sint64Item) String() string { return proto.CompactTextString(m) }
func (*Sint64Item) ProtoMessage()    {}
func (*Sint64Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{7}
}

func (m *Sint64Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sint64Item.Unmarshal(m, b)
}
func (m *Sint64Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sint64Item.Marshal(b, m, deterministic)
}
func (m *Sint64Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sint64Item.Merge(m, src)
}
func (m *Sint64Item) XXX_Size() int {
	return xxx_messageInfo_Sint64Item.Size(m)
}
func (m *Sint64Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Sint64Item.DiscardUnknown(m)
}

var xxx_messageInfo_Sint64Item proto.InternalMessageInfo

func (m *Sint64Item) GetValue1() int64 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *Sint64Item) GetValue2() int64 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *Sint64Item) GetValue3() int64 {
	if m != nil {
		return m.Value3
	}
	return 0
}

func (m *Sint64Item) GetValue4() int64 {
	if m != nil {
		return m.Value4
	}
	return 0
}

func (m *Sint64Item) GetValue5() int64 {
	if m != nil {
		return m.Value5
	}
	return 0
}

type Fixed32Item struct {
	Value1               uint32   `protobuf:"fixed32,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               uint32   `protobuf:"fixed32,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               uint32   `protobuf:"fixed32,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               uint32   `protobuf:"fixed32,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               uint32   `protobuf:"fixed32,5,opt,name=value5,proto3" json:"value5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fixed32Item) Reset()         { *m = Fixed32Item{} }
func (m *Fixed32Item) String() string { return proto.CompactTextString(m) }
func (*Fixed32Item) ProtoMessage()    {}
func (*Fixed32Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{8}
}

func (m *Fixed32Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fixed32Item.Unmarshal(m, b)
}
func (m *Fixed32Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fixed32Item.Marshal(b, m, deterministic)
}
func (m *Fixed32Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fixed32Item.Merge(m, src)
}
func (m *Fixed32Item) XXX_Size() int {
	return xxx_messageInfo_Fixed32Item.Size(m)
}
func (m *Fixed32Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Fixed32Item.DiscardUnknown(m)
}

var xxx_messageInfo_Fixed32Item proto.InternalMessageInfo

func (m *Fixed32Item) GetValue1() uint32 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *Fixed32Item) GetValue2() uint32 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *Fixed32Item) GetValue3() uint32 {
	if m != nil {
		return m.Value3
	}
	return 0
}

func (m *Fixed32Item) GetValue4() uint32 {
	if m != nil {
		return m.Value4
	}
	return 0
}

func (m *Fixed32Item) GetValue5() uint32 {
	if m != nil {
		return m.Value5
	}
	return 0
}

type Fixed64Item struct {
	Value1               uint64   `protobuf:"fixed64,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               uint64   `protobuf:"fixed64,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               uint64   `protobuf:"fixed64,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               uint64   `protobuf:"fixed64,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               uint64   `protobuf:"fixed64,5,opt,name=value5,proto3" json:"value5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fixed64Item) Reset()         { *m = Fixed64Item{} }
func (m *Fixed64Item) String() string { return proto.CompactTextString(m) }
func (*Fixed64Item) ProtoMessage()    {}
func (*Fixed64Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{9}
}

func (m *Fixed64Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fixed64Item.Unmarshal(m, b)
}
func (m *Fixed64Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fixed64Item.Marshal(b, m, deterministic)
}
func (m *Fixed64Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fixed64Item.Merge(m, src)
}
func (m *Fixed64Item) XXX_Size() int {
	return xxx_messageInfo_Fixed64Item.Size(m)
}
func (m *Fixed64Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Fixed64Item.DiscardUnknown(m)
}

var xxx_messageInfo_Fixed64Item proto.InternalMessageInfo

func (m *Fixed64Item) GetValue1() uint64 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *Fixed64Item) GetValue2() uint64 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *Fixed64Item) GetValue3() uint64 {
	if m != nil {
		return m.Value3
	}
	return 0
}

func (m *Fixed64Item) GetValue4() uint64 {
	if m != nil {
		return m.Value4
	}
	return 0
}

func (m *Fixed64Item) GetValue5() uint64 {
	if m != nil {
		return m.Value5
	}
	return 0
}

type Sfixed32Item struct {
	Value1               int32    `protobuf:"fixed32,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               int32    `protobuf:"fixed32,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               int32    `protobuf:"fixed32,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               int32    `protobuf:"fixed32,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               int32    `protobuf:"fixed32,5,opt,name=value5,proto3" json:"value5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sfixed32Item) Reset()         { *m = Sfixed32Item{} }
func (m *Sfixed32Item) String() string { return proto.CompactTextString(m) }
func (*Sfixed32Item) ProtoMessage()    {}
func (*Sfixed32Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{10}
}

func (m *Sfixed32Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sfixed32Item.Unmarshal(m, b)
}
func (m *Sfixed32Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sfixed32Item.Marshal(b, m, deterministic)
}
func (m *Sfixed32Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sfixed32Item.Merge(m, src)
}
func (m *Sfixed32Item) XXX_Size() int {
	return xxx_messageInfo_Sfixed32Item.Size(m)
}
func (m *Sfixed32Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Sfixed32Item.DiscardUnknown(m)
}

var xxx_messageInfo_Sfixed32Item proto.InternalMessageInfo

func (m *Sfixed32Item) GetValue1() int32 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *Sfixed32Item) GetValue2() int32 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *Sfixed32Item) GetValue3() int32 {
	if m != nil {
		return m.Value3
	}
	return 0
}

func (m *Sfixed32Item) GetValue4() int32 {
	if m != nil {
		return m.Value4
	}
	return 0
}

func (m *Sfixed32Item) GetValue5() int32 {
	if m != nil {
		return m.Value5
	}
	return 0
}

type Sfixed64Item struct {
	Value1               int64    `protobuf:"fixed64,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               int64    `protobuf:"fixed64,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               int64    `protobuf:"fixed64,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               int64    `protobuf:"fixed64,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               int64    `protobuf:"fixed64,5,opt,name=value5,proto3" json:"value5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sfixed64Item) Reset()         { *m = Sfixed64Item{} }
func (m *Sfixed64Item) String() string { return proto.CompactTextString(m) }
func (*Sfixed64Item) ProtoMessage()    {}
func (*Sfixed64Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{11}
}

func (m *Sfixed64Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sfixed64Item.Unmarshal(m, b)
}
func (m *Sfixed64Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sfixed64Item.Marshal(b, m, deterministic)
}
func (m *Sfixed64Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sfixed64Item.Merge(m, src)
}
func (m *Sfixed64Item) XXX_Size() int {
	return xxx_messageInfo_Sfixed64Item.Size(m)
}
func (m *Sfixed64Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Sfixed64Item.DiscardUnknown(m)
}

var xxx_messageInfo_Sfixed64Item proto.InternalMessageInfo

func (m *Sfixed64Item) GetValue1() int64 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *Sfixed64Item) GetValue2() int64 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *Sfixed64Item) GetValue3() int64 {
	if m != nil {
		return m.Value3
	}
	return 0
}

func (m *Sfixed64Item) GetValue4() int64 {
	if m != nil {
		return m.Value4
	}
	return 0
}

func (m *Sfixed64Item) GetValue5() int64 {
	if m != nil {
		return m.Value5
	}
	return 0
}

type BoolItem struct {
	Value1               bool     `protobuf:"varint,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               bool     `protobuf:"varint,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               bool     `protobuf:"varint,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               bool     `protobuf:"varint,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               bool     `protobuf:"varint,5,opt,name=value5,proto3" json:"value5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolItem) Reset()         { *m = BoolItem{} }
func (m *BoolItem) String() string { return proto.CompactTextString(m) }
func (*BoolItem) ProtoMessage()    {}
func (*BoolItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{12}
}

func (m *BoolItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolItem.Unmarshal(m, b)
}
func (m *BoolItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolItem.Marshal(b, m, deterministic)
}
func (m *BoolItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolItem.Merge(m, src)
}
func (m *BoolItem) XXX_Size() int {
	return xxx_messageInfo_BoolItem.Size(m)
}
func (m *BoolItem) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolItem.DiscardUnknown(m)
}

var xxx_messageInfo_BoolItem proto.InternalMessageInfo

func (m *BoolItem) GetValue1() bool {
	if m != nil {
		return m.Value1
	}
	return false
}

func (m *BoolItem) GetValue2() bool {
	if m != nil {
		return m.Value2
	}
	return false
}

func (m *BoolItem) GetValue3() bool {
	if m != nil {
		return m.Value3
	}
	return false
}

func (m *BoolItem) GetValue4() bool {
	if m != nil {
		return m.Value4
	}
	return false
}

func (m *BoolItem) GetValue5() bool {
	if m != nil {
		return m.Value5
	}
	return false
}

type StringItem struct {
	Value1               string   `protobuf:"bytes,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               string   `protobuf:"bytes,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               string   `protobuf:"bytes,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               string   `protobuf:"bytes,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               string   `protobuf:"bytes,5,opt,name=value5,proto3" json:"value5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringItem) Reset()         { *m = StringItem{} }
func (m *StringItem) String() string { return proto.CompactTextString(m) }
func (*StringItem) ProtoMessage()    {}
func (*StringItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{13}
}

func (m *StringItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringItem.Unmarshal(m, b)
}
func (m *StringItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringItem.Marshal(b, m, deterministic)
}
func (m *StringItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringItem.Merge(m, src)
}
func (m *StringItem) XXX_Size() int {
	return xxx_messageInfo_StringItem.Size(m)
}
func (m *StringItem) XXX_DiscardUnknown() {
	xxx_messageInfo_StringItem.DiscardUnknown(m)
}

var xxx_messageInfo_StringItem proto.InternalMessageInfo

func (m *StringItem) GetValue1() string {
	if m != nil {
		return m.Value1
	}
	return ""
}

func (m *StringItem) GetValue2() string {
	if m != nil {
		return m.Value2
	}
	return ""
}

func (m *StringItem) GetValue3() string {
	if m != nil {
		return m.Value3
	}
	return ""
}

func (m *StringItem) GetValue4() string {
	if m != nil {
		return m.Value4
	}
	return ""
}

func (m *StringItem) GetValue5() string {
	if m != nil {
		return m.Value5
	}
	return ""
}

type BytesItem struct {
	Value1               []byte   `protobuf:"bytes,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               []byte   `protobuf:"bytes,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               []byte   `protobuf:"bytes,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               []byte   `protobuf:"bytes,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               []byte   `protobuf:"bytes,5,opt,name=value5,proto3" json:"value5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BytesItem) Reset()         { *m = BytesItem{} }
func (m *BytesItem) String() string { return proto.CompactTextString(m) }
func (*BytesItem) ProtoMessage()    {}
func (*BytesItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{14}
}

func (m *BytesItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BytesItem.Unmarshal(m, b)
}
func (m *BytesItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BytesItem.Marshal(b, m, deterministic)
}
func (m *BytesItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BytesItem.Merge(m, src)
}
func (m *BytesItem) XXX_Size() int {
	return xxx_messageInfo_BytesItem.Size(m)
}
func (m *BytesItem) XXX_DiscardUnknown() {
	xxx_messageInfo_BytesItem.DiscardUnknown(m)
}

var xxx_messageInfo_BytesItem proto.InternalMessageInfo

func (m *BytesItem) GetValue1() []byte {
	if m != nil {
		return m.Value1
	}
	return nil
}

func (m *BytesItem) GetValue2() []byte {
	if m != nil {
		return m.Value2
	}
	return nil
}

func (m *BytesItem) GetValue3() []byte {
	if m != nil {
		return m.Value3
	}
	return nil
}

func (m *BytesItem) GetValue4() []byte {
	if m != nil {
		return m.Value4
	}
	return nil
}

func (m *BytesItem) GetValue5() []byte {
	if m != nil {
		return m.Value5
	}
	return nil
}

type RepeatedItem struct {
	Values               []float64 `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RepeatedItem) Reset()         { *m = RepeatedItem{} }
func (m *RepeatedItem) String() string { return proto.CompactTextString(m) }
func (*RepeatedItem) ProtoMessage()    {}
func (*RepeatedItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{15}
}

func (m *RepeatedItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedItem.Unmarshal(m, b)
}
func (m *RepeatedItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedItem.Marshal(b, m, deterministic)
}
func (m *RepeatedItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedItem.Merge(m, src)
}
func (m *RepeatedItem) XXX_Size() int {
	return xxx_messageInfo_RepeatedItem.Size(m)
}
func (m *RepeatedItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedItem.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedItem proto.InternalMessageInfo

func (m *RepeatedItem) GetValues() []float64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type RecordItem struct {
	Inner                *InnerRecordItem `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	Num                  int32            `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RecordItem) Reset()         { *m = RecordItem{} }
func (m *RecordItem) String() string { return proto.CompactTextString(m) }
func (*RecordItem) ProtoMessage()    {}
func (*RecordItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{16}
}

func (m *RecordItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordItem.Unmarshal(m, b)
}
func (m *RecordItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordItem.Marshal(b, m, deterministic)
}
func (m *RecordItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordItem.Merge(m, src)
}
func (m *RecordItem) XXX_Size() int {
	return xxx_messageInfo_RecordItem.Size(m)
}
func (m *RecordItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordItem.DiscardUnknown(m)
}

var xxx_messageInfo_RecordItem proto.InternalMessageInfo

func (m *RecordItem) GetInner() *InnerRecordItem {
	if m != nil {
		return m.Inner
	}
	return nil
}

func (m *RecordItem) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type InnerRecordItem struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerRecordItem) Reset()         { *m = InnerRecordItem{} }
func (m *InnerRecordItem) String() string { return proto.CompactTextString(m) }
func (*InnerRecordItem) ProtoMessage()    {}
func (*InnerRecordItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{17}
}

func (m *InnerRecordItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerRecordItem.Unmarshal(m, b)
}
func (m *InnerRecordItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerRecordItem.Marshal(b, m, deterministic)
}
func (m *InnerRecordItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerRecordItem.Merge(m, src)
}
func (m *InnerRecordItem) XXX_Size() int {
	return xxx_messageInfo_InnerRecordItem.Size(m)
}
func (m *InnerRecordItem) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerRecordItem.DiscardUnknown(m)
}

var xxx_messageInfo_InnerRecordItem proto.InternalMessageInfo

func (m *InnerRecordItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InnerRecordItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*DoubleItem)(nil), "protocol.double_item")
	proto.RegisterType((*FloatItem)(nil), "protocol.float_item")
	proto.RegisterType((*Int32Item)(nil), "protocol.int32_item")
	proto.RegisterType((*Int64Item)(nil), "protocol.int64_item")
	proto.RegisterType((*Uint32Item)(nil), "protocol.uint32_item")
	proto.RegisterType((*Uint64Item)(nil), "protocol.uint64_item")
	proto.RegisterType((*Sint32Item)(nil), "protocol.sint32_item")
	proto.RegisterType((*Sint64Item)(nil), "protocol.sint64_item")
	proto.RegisterType((*Fixed32Item)(nil), "protocol.fixed32_item")
	proto.RegisterType((*Fixed64Item)(nil), "protocol.fixed64_item")
	proto.RegisterType((*Sfixed32Item)(nil), "protocol.sfixed32_item")
	proto.RegisterType((*Sfixed64Item)(nil), "protocol.sfixed64_item")
	proto.RegisterType((*BoolItem)(nil), "protocol.bool_item")
	proto.RegisterType((*StringItem)(nil), "protocol.string_item")
	proto.RegisterType((*BytesItem)(nil), "protocol.bytes_item")
	proto.RegisterType((*RepeatedItem)(nil), "protocol.repeated_item")
	proto.RegisterType((*RecordItem)(nil), "protocol.record_item")
	proto.RegisterType((*InnerRecordItem)(nil), "protocol.inner_record_item")
}

func init() {
	proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e)
}

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd6, 0xcb, 0x8e, 0x9b, 0x30,
	0x18, 0x05, 0x60, 0xd9, 0xe6, 0xfa, 0x07, 0x0a, 0x78, 0x51, 0x21, 0x75, 0x33, 0xca, 0xa6, 0x5d,
	0x45, 0x9a, 0x24, 0xd3, 0xbe, 0x47, 0x5e, 0x60, 0x94, 0x0c, 0x9e, 0x0a, 0x89, 0xe0, 0x11, 0x98,
	0xaa, 0x5d, 0xf7, 0xf6, 0xda, 0x55, 0x28, 0xb5, 0xa0, 0xf8, 0xcc, 0x0a, 0x73, 0xf4, 0x4b, 0x7c,
	0x3a, 0x5c, 0x0c, 0x91, 0x51, 0xbd, 0xd9, 0xbd, 0x74, 0xda, 0x68, 0x19, 0x8d, 0x87, 0x27, 0xdd,
	0x6c, 0x7f, 0x32, 0xda, 0x54, 0x7a, 0xb8, 0x34, 0xea, 0xb1, 0x36, 0xea, 0x2a, 0xdf, 0x52, 0xf0,
	0xe5, 0xdc, 0x0c, 0xea, 0xbe, 0x64, 0x77, 0xec, 0x03, 0x3b, 0x4d, 0x67, 0x36, 0xdf, 0x97, 0x7c,
	0x96, 0xef, 0x6d, 0x7e, 0x28, 0xc5, 0x2c, 0x3f, 0xd8, 0xfc, 0x58, 0x7a, 0xb3, 0xfc, 0x68, 0xf3,
	0x87, 0xd2, 0x9f, 0xe5, 0x0f, 0xdb, 0x1f, 0x8c, 0xe8, 0xb9, 0xd1, 0x67, 0xe3, 0x62, 0x70, 0xc0,
	0xe0, 0x80, 0xc1, 0x01, 0x83, 0x03, 0x06, 0x5f, 0x30, 0xea, 0xd6, 0x1c, 0xf6, 0x2e, 0x86, 0x0f,
	0x18, 0x3e, 0x60, 0xf8, 0x80, 0xe1, 0x03, 0x86, 0xff, 0x3f, 0xe3, 0xe3, 0xd1, 0xc5, 0x10, 0x80,
	0x21, 0x00, 0x43, 0x00, 0x86, 0x00, 0x0c, 0x61, 0x19, 0xb7, 0x87, 0x63, 0x80, 0x75, 0xa4, 0xc0,
	0x91, 0x02, 0x47, 0x0a, 0x1c, 0x29, 0x70, 0xa4, 0x2b, 0x87, 0xbb, 0x0f, 0x0f, 0x38, 0x3c, 0xe0,
	0xf0, 0x80, 0xc3, 0x03, 0x0e, 0x6f, 0xe1, 0xe8, 0x61, 0x1f, 0x05, 0x70, 0x14, 0xc0, 0x51, 0x00,
	0x47, 0x01, 0x1c, 0xc5, 0xca, 0xe1, 0xee, 0x43, 0x02, 0x87, 0x04, 0x0e, 0x09, 0x1c, 0x12, 0x38,
	0xa4, 0x75, 0xfc, 0x62, 0x94, 0x3c, 0xd7, 0x5f, 0x55, 0xe5, 0x2e, 0x24, 0x04, 0x90, 0x10, 0x40,
	0x42, 0x00, 0x09, 0x01, 0x24, 0x5c, 0x43, 0xdc, 0x8d, 0x04, 0x00, 0x12, 0x00, 0x48, 0x00, 0x20,
	0x01, 0x80, 0x04, 0x16, 0xf2, 0x9b, 0x51, 0xda, 0xbf, 0x52, 0x49, 0x06, 0x24, 0x19, 0x90, 0x64,
	0x40, 0x92, 0x01, 0x49, 0xe6, 0x90, 0xb8, 0x3b, 0xc9, 0x81, 0x24, 0x07, 0x92, 0x1c, 0x48, 0x72,
	0x20, 0xc9, 0xad, 0xe4, 0x3b, 0xa3, 0xf8, 0xa2, 0x75, 0xe3, 0x52, 0x44, 0x40, 0x11, 0x01, 0x45,
	0x04, 0x14, 0x11, 0x50, 0x44, 0xcb, 0x77, 0xc6, 0x74, 0x75, 0xfb, 0xd9, 0xe5, 0x88, 0x81, 0x23,
	0x06, 0x8e, 0x18, 0x38, 0x62, 0xe0, 0x88, 0x17, 0x9f, 0xf6, 0xcb, 0x37, 0xa3, 0x7a, 0x17, 0x23,
	0x01, 0x8c, 0x04, 0x30, 0x12, 0xc0, 0x48, 0x00, 0x23, 0xb1, 0x8c, 0xf7, 0x94, 0x76, 0xea, 0x45,
	0x9d, 0x8d, 0xaa, 0x96, 0x90, 0xbe, 0x64, 0x77, 0xc2, 0x6e, 0xcc, 0xfd, 0xf6, 0x44, 0x9b, 0x4e,
	0x3d, 0xe9, 0x6e, 0x1a, 0xbb, 0x27, 0xbf, 0x6e, 0x5b, 0xd5, 0x8d, 0xdc, 0xcd, 0xfe, 0xdd, 0xee,
	0xdf, 0x9f, 0xc4, 0x6e, 0x8c, 0x1f, 0x67, 0xb3, 0xa7, 0xbf, 0x93, 0x32, 0x27, 0xd1, 0x0e, 0xd7,
	0x69, 0xa7, 0xbc, 0x2d, 0xb7, 0x9f, 0xa8, 0x58, 0x4d, 0xcb, 0x37, 0xc4, 0xeb, 0x6a, 0xda, 0x67,
	0x79, 0x5d, 0x49, 0x49, 0x5e, 0x7b, 0xbe, 0xaa, 0xe9, 0x36, 0x8c, 0xeb, 0x4b, 0x30, 0x5e, 0xed,
	0xf0, 0x27, 0x00, 0x00, 0xff, 0xff, 0x95, 0x58, 0x88, 0xc4, 0xcc, 0x08, 0x00, 0x00,
}
